lista = {
'mbauchilecl.txt', ...
'mbauchileclplan-de-estudios.txt', ...
'mbauchileclfinanciamiento-y-becas.txt', ...
'mbauchilecldescargar-folleto.txt', ...
'mbauchilecltipojornada-completa-y-media-jornada.txt', ...
'mbauchilecl20130613mba-uchile-lider-en-ranking-latinoamericano.txt', ...
'mbauchileclplataforma-laboral.txt', ...
'mbauchileclservicio-medico.txt', ...
'mbauchileclcontenido-cursos.txt', ...
'mbauchilecltipojornada-parcial.txt', ...
'mbauchilecltodosnoticiaspage2.txt', ...
'mbauchileclinvitados.txt', ...
'mbauchileclmapa-ubicacion.txt', ...
'mbauchileclacademicosandres-weintraub.txt', ...
'mbauchilecltestimoniosfelipe-sepulveda.txt', ...
'mbauchileclipad.txt', ...
'mbauchileclpostulacion-online.txt', ...
'mbauchilecladmision.txt', ...
'mbauchilecldoble-grado.txt', ...
'mbauchileclcaracteristicas.txt', ...
'mbauchileclcontacto.txt', ...
'mbauchileclgeneraciones.txt', ...
'mbauchileclperfil-alumnos.txt', ...
'mbauchileclporque-elegirnos.txt', ...
'mbauchileclformularios.txt', ...
'mbauchileclreglamento.txt', ...
'mbauchileclpropuesta-academica.txt', ...
'mbauchileclu-cursos.txt', ...
'mbauchileclegresados.txt', ...
'mbauchileclcorporacion-egresados.txt', ...
'mbauchileclquienes-participan.txt', ...
'mbauchileclbiblioteca.txt', ...
'mbauchileclmetodologia.txt', ...
};

for i=1:length(lista)

    fid = fopen(lista{i},'r');
    txt = textscan(fid,'%s %f %f %f %f %f %f %f %f','delimiter',',');
    fclose(fid);
    
    types = unique(txt{1});
    bodybin = zeros(length(txt{1}),length(types));
    for j = 1:length(types)
        bodybin(:,j) = strcmp(txt{1},types{j});
    end
    
    X = [sqrt(txt{4}.*txt{5}) bodybin txt{6} txt{7}];
    k = 4;
    Y = [txt{2} txt{3} txt{4} txt{5} txt{6} txt{7}];
    
    IDX = kmeans(X,k,'start','sample','EmptyAction','singleton');
    
    data = [Y IDX txt{8} txt{9}];
    
    fileID = fopen(['cluster' lista{i}],'w');
    formatSpec = '%s,%d,%d,%d,%d,%d,%d,%d,%d,%d\n';
    [nrows,ncols] = size(data);
    for row = 1:nrows
        r = [txt{1}(row) data(row,1) data(row,2) data(row,3) data(row,4) data(row,5) data(row,6) data(row,7) data(row,8) data(row,9)];
        fprintf(fileID,formatSpec,r{1,:});
    end
    fclose(fileID);
    
    %csvwrite(['cluster' lista{i}],data);
end
